services:
  app:
    image: ${BACKEND_DOCKER_IMAGE}
    env_file: .env.dev
    ports:
      - ${PUBLIC_PORT}:${PUBLIC_PORT}
    networks:
      - dev

networks:
  dev:
    driver: bridge
    external: true
