services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
      - ${PUBLIC_PORT}:${PUBLIC_PORT}
  redis:
    image: redis:8.6.2-alpine
    ports:
      - ${REDIS_EXTERNAL_PORT}:6379

