services:
  app:
    image: ${BACKEND_DOCKER_IMAGE}
    env_file: .env.prod
    ports:
      - ${PUBLIC_PORT}:${PUBLIC_PORT}
    networks:
      - prod

networks:
  prod:
    driver: bridge
    external: true
