bind 127.0.0.1 ::1
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300


requirepass "admin"


daemonize no
supervised systemd
pidfile /run/redis/redis-server.pid


loglevel notice
logfile ""
syslog-enabled no


save 900 1
save 300 10
save 60 10000

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /var/lib/redis


appendonly yes
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-use-rdb-preamble yes


maxmemory 1gb


maxmemory-policy allkeys-lru


lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes


databases 16
hz 10
dynamic-hz yes


maxclients 10000


replica-read-only yes
repl-diskless-sync yes
repl-diskless-sync-delay 5


slowlog-log-slower-than 10000
slowlog-max-len 256


client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60


activedefrag yes
